---
language: node_js
node_js:
    - "4"

sudo: required

cache:
    directories:
        - node_modules

env:
    - CXX=g++-4.8
    - EMBER_TRY_SCENARIO=default
    - EMBER_TRY_SCENARIO=ember-release

addons:
  apt:
    sources:
        - ubuntu-toolchain-r-test
    packages:
        - g++-4.8

matrix:
    fast_finish: true
    allow_failures:
        - env: EMBER_TRY_SCENARIO=ember-release

before_install:
    - "sudo rm -rf /usr/local/phantomjs"
    - "npm config set spin false"
    - "npm install -g npm@^2"

install:
    - npm install -g bower
    - npm install
    - bower install

script:
    - npm run lint-all
    - ember ember-cli-jsdoc
    - ember try $EMBER_TRY_SCENARIO test
