---
language: node_js
node_js:
    - "5"

sudo: required

cache: false

env:
    - CXX=g++-4.8
    - EMBER_TRY_SCENARIO=default
    - EMBER_TRY_SCENARIO=ember-release

addons:
  apt:
    sources:
        - ubuntu-toolchain-r-test
        - google-chrome
    packages:
        - g++-4.8
        - google-chrome-stable

matrix:
    fast_finish: true
    allow_failures:
        - env: EMBER_TRY_SCENARIO=ember-release

before_install:
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"
    - "npm config set spin false"
    - "npm install -g npm@^2"


install:
    - npm install -g bower
    - npm install
    - bower install

before_script:
    - "ls -laF node_modules/.bin"

script:
    - npm run lint-all
    - ember ember-cli-jsdoc
    - ember try $EMBER_TRY_SCENARIO test
